import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Calendar from 'components/calendar'
import React, { useState } from 'react'
import MultiSelect from 'components/multiSelect'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const selectedTags = tags => {
		console.log(tags);
	};
  return (
    <>
      <Head>
        <title>Calendar and Multi Select Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Calendar />
      <MultiSelect selectedTags={selectedTags}  tags={['1918123']}/>
    </>
  )
}
